### ISSUE TITLE
Very similar project

### ISSUE THREAD

**Issue by mizzao** [dburles/meteor-presence#1]
Hey @dburles,

I just saw this repo and wondered if you know about my project at https://github.com/mizzao/meteor-user-status. Your rewrite, as of right now, looks really similar to that code, including what happens in the main `publish` function. Would it make sense to potentially collaborate and maintain the same project rather than two projects that do pretty much the same thing?

**Comment by dandv** [comment]
I was looking for a native, self-hosted, Meteor analytics solution, and have found nothing. The closes would be these two packages and @andrewreedy's [visit-tracker](https://atmospherejs.com/bigdata/visit-tracker). Thoughts?
